### ISSUE TITLE
pylint and ci

### ISSUE THREAD

**Issue by maximilianbehr** [ManuelMBaumann/vanilla-python-ci#5]
https://jeffknupp.com/blog/2016/12/09/how-python-linters-will-save-your-large-python-project/
it will check if pep standards are violated and so on.

* setup pylint for your project
* do a pylint run during ci

**Comment by maximilianbehr** [comment]
![index](https://user-images.githubusercontent.com/26087188/65377716-49155380-dcb0-11e9-88af-f534ca8ccb8a.png)

**Comment by ManuelMBaumann** [comment]
************* Module vanilla-python-ci.main
C:  5, 0: Trailing whitespace (trailing-whitespace)
C: 10, 0: Trailing whitespace (trailing-whitespace)
C: 15, 0: Trailing whitespace (trailing-whitespace)
C:  1, 0: Missing module docstring (missing-docstring)
C:  3, 0: Invalid argument name "x" (invalid-name)
E: 17,11: Module 'numpy' has no 'power' member (no-member)
C: 19, 0: Invalid argument name "x" (invalid-name)
C: 19, 0: Missing function docstring (missing-docstring)

-------------------------------------
Your code has been rated at -14.00/10

**Comment by ManuelMBaumann** [comment]
No config file found, using default configuration

-------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 8.00/10, +2.00)
